output:
  sort-results: true

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

linters-settings:
  gci:
    local-prefixes: github.com/flatcar-linux/fleetlock

linters:
  disable-all: false
  disable:
    # We do not have clearly defined error types yet.
    - goerr113
    # We do not require all used structs to have all fields initialized.
    - exhaustivestruct
    # Temporarily disable reporting linters.
    - errcheck
    - govet
    # This linters has been deprecated.
    - interfacer
    - maligned
    - golint
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    #- dupl
    - durationcheck
    #- errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    #- gochecknoglobals
    #- gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    #- gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - ifshort
    - importas
    - ineffassign
    #- lll
    - makezero
    #- misspell
    - nakedret
    - nestif
    - nilerr
    #- nlreturn
    #- noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    #- revive
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    #- stylecheck
    #- tagliatelle
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - wastedassign
    - whitespace
    - wrapcheck
    #- wsl
