name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.42
    steps:
      - uses: actions/checkout@v2

      - name: Check linters are up to date
        run: make test-update-linters

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
